version: "3"
services:
  app:
    container_name: "tawazun-app"
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=database
      - DB_PORT=3306
      - DB_NAME=tawazun-db
      - DB_USERNAME=root
      - DB_PASSWORD=password123
    depends_on:
      - database
  database:
    image: "mysql"
    container_name: "tawazun-db"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password321
      - MYSQL_DATABASE=tawazun-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password123